game: hangman_sct

agents:
  - PrivateCoTAgent:
      name: test_private_cot
  - WorkflowAgent:
      strategy: overwrite
      name: test_workflow_overwrite_agent
  - LightMemAgent:
      name: test_lightmem_agent
      lightmem_config_path: ./config/lightmem_config_gptoss_20b.yaml
  
num_trials: 1

providers:
  main: gpt_oss_20b_openrouter
  concurrency: 0  # Sequential mode only

results_dir: results/test_tracker/hangman_sct/

sct:
  t_fork: 2  # Short test - fork after 2 turns
  T_max: 10
  random_seed: 42
  n_candidate_secrets: 3  # Just 3 branches to keep it fast

  stateless_candidates:
    method: deterministic

